//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eventkalender.PK.EventkalenderReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Nation", Namespace="http://www.ics.lu.se.cali/")]
    [System.SerializableAttribute()]
    public partial class Nation : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Eventkalender.PK.EventkalenderReference.Event[] EventsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public Eventkalender.PK.EventkalenderReference.Event[] Events {
            get {
                return this.EventsField;
            }
            set {
                if ((object.ReferenceEquals(this.EventsField, value) != true)) {
                    this.EventsField = value;
                    this.RaisePropertyChanged("Events");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Event", Namespace="http://www.ics.lu.se.cali/")]
    [System.SerializableAttribute()]
    public partial class Event : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SummaryField;
        
        private System.DateTime StartTimeField;
        
        private System.DateTime EndTimeField;
        
        private int NationIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Eventkalender.PK.EventkalenderReference.Nation NationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Eventkalender.PK.EventkalenderReference.Person[] PersonsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Summary {
            get {
                return this.SummaryField;
            }
            set {
                if ((object.ReferenceEquals(this.SummaryField, value) != true)) {
                    this.SummaryField = value;
                    this.RaisePropertyChanged("Summary");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.DateTime StartTime {
            get {
                return this.StartTimeField;
            }
            set {
                if ((this.StartTimeField.Equals(value) != true)) {
                    this.StartTimeField = value;
                    this.RaisePropertyChanged("StartTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.DateTime EndTime {
            get {
                return this.EndTimeField;
            }
            set {
                if ((this.EndTimeField.Equals(value) != true)) {
                    this.EndTimeField = value;
                    this.RaisePropertyChanged("EndTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int NationId {
            get {
                return this.NationIdField;
            }
            set {
                if ((this.NationIdField.Equals(value) != true)) {
                    this.NationIdField = value;
                    this.RaisePropertyChanged("NationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public Eventkalender.PK.EventkalenderReference.Nation Nation {
            get {
                return this.NationField;
            }
            set {
                if ((object.ReferenceEquals(this.NationField, value) != true)) {
                    this.NationField = value;
                    this.RaisePropertyChanged("Nation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public Eventkalender.PK.EventkalenderReference.Person[] Persons {
            get {
                return this.PersonsField;
            }
            set {
                if ((object.ReferenceEquals(this.PersonsField, value) != true)) {
                    this.PersonsField = value;
                    this.RaisePropertyChanged("Persons");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Person", Namespace="http://www.ics.lu.se.cali/")]
    [System.SerializableAttribute()]
    public partial class Person : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Eventkalender.PK.EventkalenderReference.Event[] EventsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public Eventkalender.PK.EventkalenderReference.Event[] Events {
            get {
                return this.EventsField;
            }
            set {
                if ((object.ReferenceEquals(this.EventsField, value) != true)) {
                    this.EventsField = value;
                    this.RaisePropertyChanged("Events");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.ics.lu.se.cali/", ConfigurationName="EventkalenderReference.EventkalenderServiceSoap")]
    public interface EventkalenderServiceSoap {
        
        // CODEGEN: Generating message contract since element name GetNationResult from namespace http://www.ics.lu.se.cali/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ics.lu.se.cali/GetNation", ReplyAction="*")]
        Eventkalender.PK.EventkalenderReference.GetNationResponse GetNation(Eventkalender.PK.EventkalenderReference.GetNationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ics.lu.se.cali/GetNation", ReplyAction="*")]
        System.Threading.Tasks.Task<Eventkalender.PK.EventkalenderReference.GetNationResponse> GetNationAsync(Eventkalender.PK.EventkalenderReference.GetNationRequest request);
        
        // CODEGEN: Generating message contract since element name GetNationsResult from namespace http://www.ics.lu.se.cali/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ics.lu.se.cali/GetNations", ReplyAction="*")]
        Eventkalender.PK.EventkalenderReference.GetNationsResponse GetNations(Eventkalender.PK.EventkalenderReference.GetNationsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ics.lu.se.cali/GetNations", ReplyAction="*")]
        System.Threading.Tasks.Task<Eventkalender.PK.EventkalenderReference.GetNationsResponse> GetNationsAsync(Eventkalender.PK.EventkalenderReference.GetNationsRequest request);
        
        // CODEGEN: Generating message contract since element name name from namespace http://www.ics.lu.se.cali/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ics.lu.se.cali/AddNation", ReplyAction="*")]
        Eventkalender.PK.EventkalenderReference.AddNationResponse AddNation(Eventkalender.PK.EventkalenderReference.AddNationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ics.lu.se.cali/AddNation", ReplyAction="*")]
        System.Threading.Tasks.Task<Eventkalender.PK.EventkalenderReference.AddNationResponse> AddNationAsync(Eventkalender.PK.EventkalenderReference.AddNationRequest request);
        
        // CODEGEN: Generating message contract since element name name from namespace http://www.ics.lu.se.cali/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ics.lu.se.cali/AddEvent", ReplyAction="*")]
        Eventkalender.PK.EventkalenderReference.AddEventResponse AddEvent(Eventkalender.PK.EventkalenderReference.AddEventRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ics.lu.se.cali/AddEvent", ReplyAction="*")]
        System.Threading.Tasks.Task<Eventkalender.PK.EventkalenderReference.AddEventResponse> AddEventAsync(Eventkalender.PK.EventkalenderReference.AddEventRequest request);
        
        // CODEGEN: Generating message contract since element name GetEventResult from namespace http://www.ics.lu.se.cali/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ics.lu.se.cali/GetEvent", ReplyAction="*")]
        Eventkalender.PK.EventkalenderReference.GetEventResponse GetEvent(Eventkalender.PK.EventkalenderReference.GetEventRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ics.lu.se.cali/GetEvent", ReplyAction="*")]
        System.Threading.Tasks.Task<Eventkalender.PK.EventkalenderReference.GetEventResponse> GetEventAsync(Eventkalender.PK.EventkalenderReference.GetEventRequest request);
        
        // CODEGEN: Generating message contract since element name GetEventsResult from namespace http://www.ics.lu.se.cali/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ics.lu.se.cali/GetEvents", ReplyAction="*")]
        Eventkalender.PK.EventkalenderReference.GetEventsResponse GetEvents(Eventkalender.PK.EventkalenderReference.GetEventsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ics.lu.se.cali/GetEvents", ReplyAction="*")]
        System.Threading.Tasks.Task<Eventkalender.PK.EventkalenderReference.GetEventsResponse> GetEventsAsync(Eventkalender.PK.EventkalenderReference.GetEventsRequest request);
        
        // CODEGEN: Generating message contract since element name firstName from namespace http://www.ics.lu.se.cali/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ics.lu.se.cali/AddPerson", ReplyAction="*")]
        Eventkalender.PK.EventkalenderReference.AddPersonResponse AddPerson(Eventkalender.PK.EventkalenderReference.AddPersonRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ics.lu.se.cali/AddPerson", ReplyAction="*")]
        System.Threading.Tasks.Task<Eventkalender.PK.EventkalenderReference.AddPersonResponse> AddPersonAsync(Eventkalender.PK.EventkalenderReference.AddPersonRequest request);
        
        // CODEGEN: Generating message contract since element name GetPersonResult from namespace http://www.ics.lu.se.cali/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ics.lu.se.cali/GetPerson", ReplyAction="*")]
        Eventkalender.PK.EventkalenderReference.GetPersonResponse GetPerson(Eventkalender.PK.EventkalenderReference.GetPersonRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ics.lu.se.cali/GetPerson", ReplyAction="*")]
        System.Threading.Tasks.Task<Eventkalender.PK.EventkalenderReference.GetPersonResponse> GetPersonAsync(Eventkalender.PK.EventkalenderReference.GetPersonRequest request);
        
        // CODEGEN: Generating message contract since element name GetPersonsResult from namespace http://www.ics.lu.se.cali/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ics.lu.se.cali/GetPersons", ReplyAction="*")]
        Eventkalender.PK.EventkalenderReference.GetPersonsResponse GetPersons(Eventkalender.PK.EventkalenderReference.GetPersonsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ics.lu.se.cali/GetPersons", ReplyAction="*")]
        System.Threading.Tasks.Task<Eventkalender.PK.EventkalenderReference.GetPersonsResponse> GetPersonsAsync(Eventkalender.PK.EventkalenderReference.GetPersonsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetNationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetNation", Namespace="http://www.ics.lu.se.cali/", Order=0)]
        public Eventkalender.PK.EventkalenderReference.GetNationRequestBody Body;
        
        public GetNationRequest() {
        }
        
        public GetNationRequest(Eventkalender.PK.EventkalenderReference.GetNationRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.ics.lu.se.cali/")]
    public partial class GetNationRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public GetNationRequestBody() {
        }
        
        public GetNationRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetNationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetNationResponse", Namespace="http://www.ics.lu.se.cali/", Order=0)]
        public Eventkalender.PK.EventkalenderReference.GetNationResponseBody Body;
        
        public GetNationResponse() {
        }
        
        public GetNationResponse(Eventkalender.PK.EventkalenderReference.GetNationResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.ics.lu.se.cali/")]
    public partial class GetNationResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Eventkalender.PK.EventkalenderReference.Nation GetNationResult;
        
        public GetNationResponseBody() {
        }
        
        public GetNationResponseBody(Eventkalender.PK.EventkalenderReference.Nation GetNationResult) {
            this.GetNationResult = GetNationResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetNationsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetNations", Namespace="http://www.ics.lu.se.cali/", Order=0)]
        public Eventkalender.PK.EventkalenderReference.GetNationsRequestBody Body;
        
        public GetNationsRequest() {
        }
        
        public GetNationsRequest(Eventkalender.PK.EventkalenderReference.GetNationsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetNationsRequestBody {
        
        public GetNationsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetNationsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetNationsResponse", Namespace="http://www.ics.lu.se.cali/", Order=0)]
        public Eventkalender.PK.EventkalenderReference.GetNationsResponseBody Body;
        
        public GetNationsResponse() {
        }
        
        public GetNationsResponse(Eventkalender.PK.EventkalenderReference.GetNationsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.ics.lu.se.cali/")]
    public partial class GetNationsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Eventkalender.PK.EventkalenderReference.Nation[] GetNationsResult;
        
        public GetNationsResponseBody() {
        }
        
        public GetNationsResponseBody(Eventkalender.PK.EventkalenderReference.Nation[] GetNationsResult) {
            this.GetNationsResult = GetNationsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddNationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddNation", Namespace="http://www.ics.lu.se.cali/", Order=0)]
        public Eventkalender.PK.EventkalenderReference.AddNationRequestBody Body;
        
        public AddNationRequest() {
        }
        
        public AddNationRequest(Eventkalender.PK.EventkalenderReference.AddNationRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.ics.lu.se.cali/")]
    public partial class AddNationRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        public AddNationRequestBody() {
        }
        
        public AddNationRequestBody(string name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddNationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddNationResponse", Namespace="http://www.ics.lu.se.cali/", Order=0)]
        public Eventkalender.PK.EventkalenderReference.AddNationResponseBody Body;
        
        public AddNationResponse() {
        }
        
        public AddNationResponse(Eventkalender.PK.EventkalenderReference.AddNationResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AddNationResponseBody {
        
        public AddNationResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddEventRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddEvent", Namespace="http://www.ics.lu.se.cali/", Order=0)]
        public Eventkalender.PK.EventkalenderReference.AddEventRequestBody Body;
        
        public AddEventRequest() {
        }
        
        public AddEventRequest(Eventkalender.PK.EventkalenderReference.AddEventRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.ics.lu.se.cali/")]
    public partial class AddEventRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string summary;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.DateTime startTime;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.DateTime endTime;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int nationId;
        
        public AddEventRequestBody() {
        }
        
        public AddEventRequestBody(string name, string summary, System.DateTime startTime, System.DateTime endTime, int nationId) {
            this.name = name;
            this.summary = summary;
            this.startTime = startTime;
            this.endTime = endTime;
            this.nationId = nationId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddEventResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddEventResponse", Namespace="http://www.ics.lu.se.cali/", Order=0)]
        public Eventkalender.PK.EventkalenderReference.AddEventResponseBody Body;
        
        public AddEventResponse() {
        }
        
        public AddEventResponse(Eventkalender.PK.EventkalenderReference.AddEventResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AddEventResponseBody {
        
        public AddEventResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEventRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetEvent", Namespace="http://www.ics.lu.se.cali/", Order=0)]
        public Eventkalender.PK.EventkalenderReference.GetEventRequestBody Body;
        
        public GetEventRequest() {
        }
        
        public GetEventRequest(Eventkalender.PK.EventkalenderReference.GetEventRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.ics.lu.se.cali/")]
    public partial class GetEventRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public GetEventRequestBody() {
        }
        
        public GetEventRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEventResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetEventResponse", Namespace="http://www.ics.lu.se.cali/", Order=0)]
        public Eventkalender.PK.EventkalenderReference.GetEventResponseBody Body;
        
        public GetEventResponse() {
        }
        
        public GetEventResponse(Eventkalender.PK.EventkalenderReference.GetEventResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.ics.lu.se.cali/")]
    public partial class GetEventResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Eventkalender.PK.EventkalenderReference.Event GetEventResult;
        
        public GetEventResponseBody() {
        }
        
        public GetEventResponseBody(Eventkalender.PK.EventkalenderReference.Event GetEventResult) {
            this.GetEventResult = GetEventResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEventsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetEvents", Namespace="http://www.ics.lu.se.cali/", Order=0)]
        public Eventkalender.PK.EventkalenderReference.GetEventsRequestBody Body;
        
        public GetEventsRequest() {
        }
        
        public GetEventsRequest(Eventkalender.PK.EventkalenderReference.GetEventsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetEventsRequestBody {
        
        public GetEventsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEventsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetEventsResponse", Namespace="http://www.ics.lu.se.cali/", Order=0)]
        public Eventkalender.PK.EventkalenderReference.GetEventsResponseBody Body;
        
        public GetEventsResponse() {
        }
        
        public GetEventsResponse(Eventkalender.PK.EventkalenderReference.GetEventsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.ics.lu.se.cali/")]
    public partial class GetEventsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Eventkalender.PK.EventkalenderReference.Event[] GetEventsResult;
        
        public GetEventsResponseBody() {
        }
        
        public GetEventsResponseBody(Eventkalender.PK.EventkalenderReference.Event[] GetEventsResult) {
            this.GetEventsResult = GetEventsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddPersonRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddPerson", Namespace="http://www.ics.lu.se.cali/", Order=0)]
        public Eventkalender.PK.EventkalenderReference.AddPersonRequestBody Body;
        
        public AddPersonRequest() {
        }
        
        public AddPersonRequest(Eventkalender.PK.EventkalenderReference.AddPersonRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.ics.lu.se.cali/")]
    public partial class AddPersonRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string firstName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string lastName;
        
        public AddPersonRequestBody() {
        }
        
        public AddPersonRequestBody(string firstName, string lastName) {
            this.firstName = firstName;
            this.lastName = lastName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddPersonResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddPersonResponse", Namespace="http://www.ics.lu.se.cali/", Order=0)]
        public Eventkalender.PK.EventkalenderReference.AddPersonResponseBody Body;
        
        public AddPersonResponse() {
        }
        
        public AddPersonResponse(Eventkalender.PK.EventkalenderReference.AddPersonResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AddPersonResponseBody {
        
        public AddPersonResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPersonRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPerson", Namespace="http://www.ics.lu.se.cali/", Order=0)]
        public Eventkalender.PK.EventkalenderReference.GetPersonRequestBody Body;
        
        public GetPersonRequest() {
        }
        
        public GetPersonRequest(Eventkalender.PK.EventkalenderReference.GetPersonRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.ics.lu.se.cali/")]
    public partial class GetPersonRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public GetPersonRequestBody() {
        }
        
        public GetPersonRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPersonResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPersonResponse", Namespace="http://www.ics.lu.se.cali/", Order=0)]
        public Eventkalender.PK.EventkalenderReference.GetPersonResponseBody Body;
        
        public GetPersonResponse() {
        }
        
        public GetPersonResponse(Eventkalender.PK.EventkalenderReference.GetPersonResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.ics.lu.se.cali/")]
    public partial class GetPersonResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Eventkalender.PK.EventkalenderReference.Person GetPersonResult;
        
        public GetPersonResponseBody() {
        }
        
        public GetPersonResponseBody(Eventkalender.PK.EventkalenderReference.Person GetPersonResult) {
            this.GetPersonResult = GetPersonResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPersonsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPersons", Namespace="http://www.ics.lu.se.cali/", Order=0)]
        public Eventkalender.PK.EventkalenderReference.GetPersonsRequestBody Body;
        
        public GetPersonsRequest() {
        }
        
        public GetPersonsRequest(Eventkalender.PK.EventkalenderReference.GetPersonsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetPersonsRequestBody {
        
        public GetPersonsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPersonsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPersonsResponse", Namespace="http://www.ics.lu.se.cali/", Order=0)]
        public Eventkalender.PK.EventkalenderReference.GetPersonsResponseBody Body;
        
        public GetPersonsResponse() {
        }
        
        public GetPersonsResponse(Eventkalender.PK.EventkalenderReference.GetPersonsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.ics.lu.se.cali/")]
    public partial class GetPersonsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Eventkalender.PK.EventkalenderReference.Person[] GetPersonsResult;
        
        public GetPersonsResponseBody() {
        }
        
        public GetPersonsResponseBody(Eventkalender.PK.EventkalenderReference.Person[] GetPersonsResult) {
            this.GetPersonsResult = GetPersonsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface EventkalenderServiceSoapChannel : Eventkalender.PK.EventkalenderReference.EventkalenderServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EventkalenderServiceSoapClient : System.ServiceModel.ClientBase<Eventkalender.PK.EventkalenderReference.EventkalenderServiceSoap>, Eventkalender.PK.EventkalenderReference.EventkalenderServiceSoap {
        
        public EventkalenderServiceSoapClient() {
        }
        
        public EventkalenderServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EventkalenderServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EventkalenderServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EventkalenderServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Eventkalender.PK.EventkalenderReference.GetNationResponse Eventkalender.PK.EventkalenderReference.EventkalenderServiceSoap.GetNation(Eventkalender.PK.EventkalenderReference.GetNationRequest request) {
            return base.Channel.GetNation(request);
        }
        
        public Eventkalender.PK.EventkalenderReference.Nation GetNation(int id) {
            Eventkalender.PK.EventkalenderReference.GetNationRequest inValue = new Eventkalender.PK.EventkalenderReference.GetNationRequest();
            inValue.Body = new Eventkalender.PK.EventkalenderReference.GetNationRequestBody();
            inValue.Body.id = id;
            Eventkalender.PK.EventkalenderReference.GetNationResponse retVal = ((Eventkalender.PK.EventkalenderReference.EventkalenderServiceSoap)(this)).GetNation(inValue);
            return retVal.Body.GetNationResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Eventkalender.PK.EventkalenderReference.GetNationResponse> Eventkalender.PK.EventkalenderReference.EventkalenderServiceSoap.GetNationAsync(Eventkalender.PK.EventkalenderReference.GetNationRequest request) {
            return base.Channel.GetNationAsync(request);
        }
        
        public System.Threading.Tasks.Task<Eventkalender.PK.EventkalenderReference.GetNationResponse> GetNationAsync(int id) {
            Eventkalender.PK.EventkalenderReference.GetNationRequest inValue = new Eventkalender.PK.EventkalenderReference.GetNationRequest();
            inValue.Body = new Eventkalender.PK.EventkalenderReference.GetNationRequestBody();
            inValue.Body.id = id;
            return ((Eventkalender.PK.EventkalenderReference.EventkalenderServiceSoap)(this)).GetNationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Eventkalender.PK.EventkalenderReference.GetNationsResponse Eventkalender.PK.EventkalenderReference.EventkalenderServiceSoap.GetNations(Eventkalender.PK.EventkalenderReference.GetNationsRequest request) {
            return base.Channel.GetNations(request);
        }
        
        public Eventkalender.PK.EventkalenderReference.Nation[] GetNations() {
            Eventkalender.PK.EventkalenderReference.GetNationsRequest inValue = new Eventkalender.PK.EventkalenderReference.GetNationsRequest();
            inValue.Body = new Eventkalender.PK.EventkalenderReference.GetNationsRequestBody();
            Eventkalender.PK.EventkalenderReference.GetNationsResponse retVal = ((Eventkalender.PK.EventkalenderReference.EventkalenderServiceSoap)(this)).GetNations(inValue);
            return retVal.Body.GetNationsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Eventkalender.PK.EventkalenderReference.GetNationsResponse> Eventkalender.PK.EventkalenderReference.EventkalenderServiceSoap.GetNationsAsync(Eventkalender.PK.EventkalenderReference.GetNationsRequest request) {
            return base.Channel.GetNationsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Eventkalender.PK.EventkalenderReference.GetNationsResponse> GetNationsAsync() {
            Eventkalender.PK.EventkalenderReference.GetNationsRequest inValue = new Eventkalender.PK.EventkalenderReference.GetNationsRequest();
            inValue.Body = new Eventkalender.PK.EventkalenderReference.GetNationsRequestBody();
            return ((Eventkalender.PK.EventkalenderReference.EventkalenderServiceSoap)(this)).GetNationsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Eventkalender.PK.EventkalenderReference.AddNationResponse Eventkalender.PK.EventkalenderReference.EventkalenderServiceSoap.AddNation(Eventkalender.PK.EventkalenderReference.AddNationRequest request) {
            return base.Channel.AddNation(request);
        }
        
        public void AddNation(string name) {
            Eventkalender.PK.EventkalenderReference.AddNationRequest inValue = new Eventkalender.PK.EventkalenderReference.AddNationRequest();
            inValue.Body = new Eventkalender.PK.EventkalenderReference.AddNationRequestBody();
            inValue.Body.name = name;
            Eventkalender.PK.EventkalenderReference.AddNationResponse retVal = ((Eventkalender.PK.EventkalenderReference.EventkalenderServiceSoap)(this)).AddNation(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Eventkalender.PK.EventkalenderReference.AddNationResponse> Eventkalender.PK.EventkalenderReference.EventkalenderServiceSoap.AddNationAsync(Eventkalender.PK.EventkalenderReference.AddNationRequest request) {
            return base.Channel.AddNationAsync(request);
        }
        
        public System.Threading.Tasks.Task<Eventkalender.PK.EventkalenderReference.AddNationResponse> AddNationAsync(string name) {
            Eventkalender.PK.EventkalenderReference.AddNationRequest inValue = new Eventkalender.PK.EventkalenderReference.AddNationRequest();
            inValue.Body = new Eventkalender.PK.EventkalenderReference.AddNationRequestBody();
            inValue.Body.name = name;
            return ((Eventkalender.PK.EventkalenderReference.EventkalenderServiceSoap)(this)).AddNationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Eventkalender.PK.EventkalenderReference.AddEventResponse Eventkalender.PK.EventkalenderReference.EventkalenderServiceSoap.AddEvent(Eventkalender.PK.EventkalenderReference.AddEventRequest request) {
            return base.Channel.AddEvent(request);
        }
        
        public void AddEvent(string name, string summary, System.DateTime startTime, System.DateTime endTime, int nationId) {
            Eventkalender.PK.EventkalenderReference.AddEventRequest inValue = new Eventkalender.PK.EventkalenderReference.AddEventRequest();
            inValue.Body = new Eventkalender.PK.EventkalenderReference.AddEventRequestBody();
            inValue.Body.name = name;
            inValue.Body.summary = summary;
            inValue.Body.startTime = startTime;
            inValue.Body.endTime = endTime;
            inValue.Body.nationId = nationId;
            Eventkalender.PK.EventkalenderReference.AddEventResponse retVal = ((Eventkalender.PK.EventkalenderReference.EventkalenderServiceSoap)(this)).AddEvent(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Eventkalender.PK.EventkalenderReference.AddEventResponse> Eventkalender.PK.EventkalenderReference.EventkalenderServiceSoap.AddEventAsync(Eventkalender.PK.EventkalenderReference.AddEventRequest request) {
            return base.Channel.AddEventAsync(request);
        }
        
        public System.Threading.Tasks.Task<Eventkalender.PK.EventkalenderReference.AddEventResponse> AddEventAsync(string name, string summary, System.DateTime startTime, System.DateTime endTime, int nationId) {
            Eventkalender.PK.EventkalenderReference.AddEventRequest inValue = new Eventkalender.PK.EventkalenderReference.AddEventRequest();
            inValue.Body = new Eventkalender.PK.EventkalenderReference.AddEventRequestBody();
            inValue.Body.name = name;
            inValue.Body.summary = summary;
            inValue.Body.startTime = startTime;
            inValue.Body.endTime = endTime;
            inValue.Body.nationId = nationId;
            return ((Eventkalender.PK.EventkalenderReference.EventkalenderServiceSoap)(this)).AddEventAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Eventkalender.PK.EventkalenderReference.GetEventResponse Eventkalender.PK.EventkalenderReference.EventkalenderServiceSoap.GetEvent(Eventkalender.PK.EventkalenderReference.GetEventRequest request) {
            return base.Channel.GetEvent(request);
        }
        
        public Eventkalender.PK.EventkalenderReference.Event GetEvent(int id) {
            Eventkalender.PK.EventkalenderReference.GetEventRequest inValue = new Eventkalender.PK.EventkalenderReference.GetEventRequest();
            inValue.Body = new Eventkalender.PK.EventkalenderReference.GetEventRequestBody();
            inValue.Body.id = id;
            Eventkalender.PK.EventkalenderReference.GetEventResponse retVal = ((Eventkalender.PK.EventkalenderReference.EventkalenderServiceSoap)(this)).GetEvent(inValue);
            return retVal.Body.GetEventResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Eventkalender.PK.EventkalenderReference.GetEventResponse> Eventkalender.PK.EventkalenderReference.EventkalenderServiceSoap.GetEventAsync(Eventkalender.PK.EventkalenderReference.GetEventRequest request) {
            return base.Channel.GetEventAsync(request);
        }
        
        public System.Threading.Tasks.Task<Eventkalender.PK.EventkalenderReference.GetEventResponse> GetEventAsync(int id) {
            Eventkalender.PK.EventkalenderReference.GetEventRequest inValue = new Eventkalender.PK.EventkalenderReference.GetEventRequest();
            inValue.Body = new Eventkalender.PK.EventkalenderReference.GetEventRequestBody();
            inValue.Body.id = id;
            return ((Eventkalender.PK.EventkalenderReference.EventkalenderServiceSoap)(this)).GetEventAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Eventkalender.PK.EventkalenderReference.GetEventsResponse Eventkalender.PK.EventkalenderReference.EventkalenderServiceSoap.GetEvents(Eventkalender.PK.EventkalenderReference.GetEventsRequest request) {
            return base.Channel.GetEvents(request);
        }
        
        public Eventkalender.PK.EventkalenderReference.Event[] GetEvents() {
            Eventkalender.PK.EventkalenderReference.GetEventsRequest inValue = new Eventkalender.PK.EventkalenderReference.GetEventsRequest();
            inValue.Body = new Eventkalender.PK.EventkalenderReference.GetEventsRequestBody();
            Eventkalender.PK.EventkalenderReference.GetEventsResponse retVal = ((Eventkalender.PK.EventkalenderReference.EventkalenderServiceSoap)(this)).GetEvents(inValue);
            return retVal.Body.GetEventsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Eventkalender.PK.EventkalenderReference.GetEventsResponse> Eventkalender.PK.EventkalenderReference.EventkalenderServiceSoap.GetEventsAsync(Eventkalender.PK.EventkalenderReference.GetEventsRequest request) {
            return base.Channel.GetEventsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Eventkalender.PK.EventkalenderReference.GetEventsResponse> GetEventsAsync() {
            Eventkalender.PK.EventkalenderReference.GetEventsRequest inValue = new Eventkalender.PK.EventkalenderReference.GetEventsRequest();
            inValue.Body = new Eventkalender.PK.EventkalenderReference.GetEventsRequestBody();
            return ((Eventkalender.PK.EventkalenderReference.EventkalenderServiceSoap)(this)).GetEventsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Eventkalender.PK.EventkalenderReference.AddPersonResponse Eventkalender.PK.EventkalenderReference.EventkalenderServiceSoap.AddPerson(Eventkalender.PK.EventkalenderReference.AddPersonRequest request) {
            return base.Channel.AddPerson(request);
        }
        
        public void AddPerson(string firstName, string lastName) {
            Eventkalender.PK.EventkalenderReference.AddPersonRequest inValue = new Eventkalender.PK.EventkalenderReference.AddPersonRequest();
            inValue.Body = new Eventkalender.PK.EventkalenderReference.AddPersonRequestBody();
            inValue.Body.firstName = firstName;
            inValue.Body.lastName = lastName;
            Eventkalender.PK.EventkalenderReference.AddPersonResponse retVal = ((Eventkalender.PK.EventkalenderReference.EventkalenderServiceSoap)(this)).AddPerson(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Eventkalender.PK.EventkalenderReference.AddPersonResponse> Eventkalender.PK.EventkalenderReference.EventkalenderServiceSoap.AddPersonAsync(Eventkalender.PK.EventkalenderReference.AddPersonRequest request) {
            return base.Channel.AddPersonAsync(request);
        }
        
        public System.Threading.Tasks.Task<Eventkalender.PK.EventkalenderReference.AddPersonResponse> AddPersonAsync(string firstName, string lastName) {
            Eventkalender.PK.EventkalenderReference.AddPersonRequest inValue = new Eventkalender.PK.EventkalenderReference.AddPersonRequest();
            inValue.Body = new Eventkalender.PK.EventkalenderReference.AddPersonRequestBody();
            inValue.Body.firstName = firstName;
            inValue.Body.lastName = lastName;
            return ((Eventkalender.PK.EventkalenderReference.EventkalenderServiceSoap)(this)).AddPersonAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Eventkalender.PK.EventkalenderReference.GetPersonResponse Eventkalender.PK.EventkalenderReference.EventkalenderServiceSoap.GetPerson(Eventkalender.PK.EventkalenderReference.GetPersonRequest request) {
            return base.Channel.GetPerson(request);
        }
        
        public Eventkalender.PK.EventkalenderReference.Person GetPerson(int id) {
            Eventkalender.PK.EventkalenderReference.GetPersonRequest inValue = new Eventkalender.PK.EventkalenderReference.GetPersonRequest();
            inValue.Body = new Eventkalender.PK.EventkalenderReference.GetPersonRequestBody();
            inValue.Body.id = id;
            Eventkalender.PK.EventkalenderReference.GetPersonResponse retVal = ((Eventkalender.PK.EventkalenderReference.EventkalenderServiceSoap)(this)).GetPerson(inValue);
            return retVal.Body.GetPersonResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Eventkalender.PK.EventkalenderReference.GetPersonResponse> Eventkalender.PK.EventkalenderReference.EventkalenderServiceSoap.GetPersonAsync(Eventkalender.PK.EventkalenderReference.GetPersonRequest request) {
            return base.Channel.GetPersonAsync(request);
        }
        
        public System.Threading.Tasks.Task<Eventkalender.PK.EventkalenderReference.GetPersonResponse> GetPersonAsync(int id) {
            Eventkalender.PK.EventkalenderReference.GetPersonRequest inValue = new Eventkalender.PK.EventkalenderReference.GetPersonRequest();
            inValue.Body = new Eventkalender.PK.EventkalenderReference.GetPersonRequestBody();
            inValue.Body.id = id;
            return ((Eventkalender.PK.EventkalenderReference.EventkalenderServiceSoap)(this)).GetPersonAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Eventkalender.PK.EventkalenderReference.GetPersonsResponse Eventkalender.PK.EventkalenderReference.EventkalenderServiceSoap.GetPersons(Eventkalender.PK.EventkalenderReference.GetPersonsRequest request) {
            return base.Channel.GetPersons(request);
        }
        
        public Eventkalender.PK.EventkalenderReference.Person[] GetPersons() {
            Eventkalender.PK.EventkalenderReference.GetPersonsRequest inValue = new Eventkalender.PK.EventkalenderReference.GetPersonsRequest();
            inValue.Body = new Eventkalender.PK.EventkalenderReference.GetPersonsRequestBody();
            Eventkalender.PK.EventkalenderReference.GetPersonsResponse retVal = ((Eventkalender.PK.EventkalenderReference.EventkalenderServiceSoap)(this)).GetPersons(inValue);
            return retVal.Body.GetPersonsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Eventkalender.PK.EventkalenderReference.GetPersonsResponse> Eventkalender.PK.EventkalenderReference.EventkalenderServiceSoap.GetPersonsAsync(Eventkalender.PK.EventkalenderReference.GetPersonsRequest request) {
            return base.Channel.GetPersonsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Eventkalender.PK.EventkalenderReference.GetPersonsResponse> GetPersonsAsync() {
            Eventkalender.PK.EventkalenderReference.GetPersonsRequest inValue = new Eventkalender.PK.EventkalenderReference.GetPersonsRequest();
            inValue.Body = new Eventkalender.PK.EventkalenderReference.GetPersonsRequestBody();
            return ((Eventkalender.PK.EventkalenderReference.EventkalenderServiceSoap)(this)).GetPersonsAsync(inValue);
        }
    }
}
