//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eventkalender.WS.ConsoleApp.EventkalenderReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Nation", Namespace="http://cali.eventkalender/")]
    [System.SerializableAttribute()]
    public partial class Nation : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Eventkalender.WS.ConsoleApp.EventkalenderReference.Event[] EventsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public Eventkalender.WS.ConsoleApp.EventkalenderReference.Event[] Events {
            get {
                return this.EventsField;
            }
            set {
                if ((object.ReferenceEquals(this.EventsField, value) != true)) {
                    this.EventsField = value;
                    this.RaisePropertyChanged("Events");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Event", Namespace="http://cali.eventkalender/")]
    [System.SerializableAttribute()]
    public partial class Event : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SummaryField;
        
        private System.DateTime StartTimeField;
        
        private System.DateTime EndTimeField;
        
        private int NationIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Eventkalender.WS.ConsoleApp.EventkalenderReference.Nation NationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Eventkalender.WS.ConsoleApp.EventkalenderReference.Person[] PersonsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Summary {
            get {
                return this.SummaryField;
            }
            set {
                if ((object.ReferenceEquals(this.SummaryField, value) != true)) {
                    this.SummaryField = value;
                    this.RaisePropertyChanged("Summary");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.DateTime StartTime {
            get {
                return this.StartTimeField;
            }
            set {
                if ((this.StartTimeField.Equals(value) != true)) {
                    this.StartTimeField = value;
                    this.RaisePropertyChanged("StartTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.DateTime EndTime {
            get {
                return this.EndTimeField;
            }
            set {
                if ((this.EndTimeField.Equals(value) != true)) {
                    this.EndTimeField = value;
                    this.RaisePropertyChanged("EndTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int NationId {
            get {
                return this.NationIdField;
            }
            set {
                if ((this.NationIdField.Equals(value) != true)) {
                    this.NationIdField = value;
                    this.RaisePropertyChanged("NationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public Eventkalender.WS.ConsoleApp.EventkalenderReference.Nation Nation {
            get {
                return this.NationField;
            }
            set {
                if ((object.ReferenceEquals(this.NationField, value) != true)) {
                    this.NationField = value;
                    this.RaisePropertyChanged("Nation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public Eventkalender.WS.ConsoleApp.EventkalenderReference.Person[] Persons {
            get {
                return this.PersonsField;
            }
            set {
                if ((object.ReferenceEquals(this.PersonsField, value) != true)) {
                    this.PersonsField = value;
                    this.RaisePropertyChanged("Persons");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Person", Namespace="http://cali.eventkalender/")]
    [System.SerializableAttribute()]
    public partial class Person : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Eventkalender.WS.ConsoleApp.EventkalenderReference.Event[] EventsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public Eventkalender.WS.ConsoleApp.EventkalenderReference.Event[] Events {
            get {
                return this.EventsField;
            }
            set {
                if ((object.ReferenceEquals(this.EventsField, value) != true)) {
                    this.EventsField = value;
                    this.RaisePropertyChanged("Events");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://cali.eventkalender/", ConfigurationName="EventkalenderReference.EventkalenderServiceSoap")]
    public interface EventkalenderServiceSoap {
        
        // CODEGEN: Generating message contract since element name path from namespace http://cali.eventkalender/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://cali.eventkalender/GetFile", ReplyAction="*")]
        Eventkalender.WS.ConsoleApp.EventkalenderReference.GetFileResponse GetFile(Eventkalender.WS.ConsoleApp.EventkalenderReference.GetFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cali.eventkalender/GetFile", ReplyAction="*")]
        System.Threading.Tasks.Task<Eventkalender.WS.ConsoleApp.EventkalenderReference.GetFileResponse> GetFileAsync(Eventkalender.WS.ConsoleApp.EventkalenderReference.GetFileRequest request);
        
        // CODEGEN: Generating message contract since element name path from namespace http://cali.eventkalender/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://cali.eventkalender/AddFile", ReplyAction="*")]
        Eventkalender.WS.ConsoleApp.EventkalenderReference.AddFileResponse AddFile(Eventkalender.WS.ConsoleApp.EventkalenderReference.AddFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cali.eventkalender/AddFile", ReplyAction="*")]
        System.Threading.Tasks.Task<Eventkalender.WS.ConsoleApp.EventkalenderReference.AddFileResponse> AddFileAsync(Eventkalender.WS.ConsoleApp.EventkalenderReference.AddFileRequest request);
        
        // CODEGEN: Generating message contract since element name GetNationResult from namespace http://cali.eventkalender/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://cali.eventkalender/GetNation", ReplyAction="*")]
        Eventkalender.WS.ConsoleApp.EventkalenderReference.GetNationResponse GetNation(Eventkalender.WS.ConsoleApp.EventkalenderReference.GetNationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cali.eventkalender/GetNation", ReplyAction="*")]
        System.Threading.Tasks.Task<Eventkalender.WS.ConsoleApp.EventkalenderReference.GetNationResponse> GetNationAsync(Eventkalender.WS.ConsoleApp.EventkalenderReference.GetNationRequest request);
        
        // CODEGEN: Generating message contract since element name GetNationsResult from namespace http://cali.eventkalender/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://cali.eventkalender/GetNations", ReplyAction="*")]
        Eventkalender.WS.ConsoleApp.EventkalenderReference.GetNationsResponse GetNations(Eventkalender.WS.ConsoleApp.EventkalenderReference.GetNationsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cali.eventkalender/GetNations", ReplyAction="*")]
        System.Threading.Tasks.Task<Eventkalender.WS.ConsoleApp.EventkalenderReference.GetNationsResponse> GetNationsAsync(Eventkalender.WS.ConsoleApp.EventkalenderReference.GetNationsRequest request);
        
        // CODEGEN: Generating message contract since element name name from namespace http://cali.eventkalender/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://cali.eventkalender/AddNation", ReplyAction="*")]
        Eventkalender.WS.ConsoleApp.EventkalenderReference.AddNationResponse AddNation(Eventkalender.WS.ConsoleApp.EventkalenderReference.AddNationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cali.eventkalender/AddNation", ReplyAction="*")]
        System.Threading.Tasks.Task<Eventkalender.WS.ConsoleApp.EventkalenderReference.AddNationResponse> AddNationAsync(Eventkalender.WS.ConsoleApp.EventkalenderReference.AddNationRequest request);
        
        // CODEGEN: Generating message contract since element name name from namespace http://cali.eventkalender/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://cali.eventkalender/AddEvent", ReplyAction="*")]
        Eventkalender.WS.ConsoleApp.EventkalenderReference.AddEventResponse AddEvent(Eventkalender.WS.ConsoleApp.EventkalenderReference.AddEventRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cali.eventkalender/AddEvent", ReplyAction="*")]
        System.Threading.Tasks.Task<Eventkalender.WS.ConsoleApp.EventkalenderReference.AddEventResponse> AddEventAsync(Eventkalender.WS.ConsoleApp.EventkalenderReference.AddEventRequest request);
        
        // CODEGEN: Generating message contract since element name GetEventResult from namespace http://cali.eventkalender/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://cali.eventkalender/GetEvent", ReplyAction="*")]
        Eventkalender.WS.ConsoleApp.EventkalenderReference.GetEventResponse GetEvent(Eventkalender.WS.ConsoleApp.EventkalenderReference.GetEventRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cali.eventkalender/GetEvent", ReplyAction="*")]
        System.Threading.Tasks.Task<Eventkalender.WS.ConsoleApp.EventkalenderReference.GetEventResponse> GetEventAsync(Eventkalender.WS.ConsoleApp.EventkalenderReference.GetEventRequest request);
        
        // CODEGEN: Generating message contract since element name GetEventsResult from namespace http://cali.eventkalender/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://cali.eventkalender/GetEvents", ReplyAction="*")]
        Eventkalender.WS.ConsoleApp.EventkalenderReference.GetEventsResponse GetEvents(Eventkalender.WS.ConsoleApp.EventkalenderReference.GetEventsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cali.eventkalender/GetEvents", ReplyAction="*")]
        System.Threading.Tasks.Task<Eventkalender.WS.ConsoleApp.EventkalenderReference.GetEventsResponse> GetEventsAsync(Eventkalender.WS.ConsoleApp.EventkalenderReference.GetEventsRequest request);
        
        // CODEGEN: Generating message contract since element name firstName from namespace http://cali.eventkalender/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://cali.eventkalender/AddPerson", ReplyAction="*")]
        Eventkalender.WS.ConsoleApp.EventkalenderReference.AddPersonResponse AddPerson(Eventkalender.WS.ConsoleApp.EventkalenderReference.AddPersonRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cali.eventkalender/AddPerson", ReplyAction="*")]
        System.Threading.Tasks.Task<Eventkalender.WS.ConsoleApp.EventkalenderReference.AddPersonResponse> AddPersonAsync(Eventkalender.WS.ConsoleApp.EventkalenderReference.AddPersonRequest request);
        
        // CODEGEN: Generating message contract since element name GetPersonResult from namespace http://cali.eventkalender/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://cali.eventkalender/GetPerson", ReplyAction="*")]
        Eventkalender.WS.ConsoleApp.EventkalenderReference.GetPersonResponse GetPerson(Eventkalender.WS.ConsoleApp.EventkalenderReference.GetPersonRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cali.eventkalender/GetPerson", ReplyAction="*")]
        System.Threading.Tasks.Task<Eventkalender.WS.ConsoleApp.EventkalenderReference.GetPersonResponse> GetPersonAsync(Eventkalender.WS.ConsoleApp.EventkalenderReference.GetPersonRequest request);
        
        // CODEGEN: Generating message contract since element name GetPersonsResult from namespace http://cali.eventkalender/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://cali.eventkalender/GetPersons", ReplyAction="*")]
        Eventkalender.WS.ConsoleApp.EventkalenderReference.GetPersonsResponse GetPersons(Eventkalender.WS.ConsoleApp.EventkalenderReference.GetPersonsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cali.eventkalender/GetPersons", ReplyAction="*")]
        System.Threading.Tasks.Task<Eventkalender.WS.ConsoleApp.EventkalenderReference.GetPersonsResponse> GetPersonsAsync(Eventkalender.WS.ConsoleApp.EventkalenderReference.GetPersonsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFile", Namespace="http://cali.eventkalender/", Order=0)]
        public Eventkalender.WS.ConsoleApp.EventkalenderReference.GetFileRequestBody Body;
        
        public GetFileRequest() {
        }
        
        public GetFileRequest(Eventkalender.WS.ConsoleApp.EventkalenderReference.GetFileRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://cali.eventkalender/")]
    public partial class GetFileRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string path;
        
        public GetFileRequestBody() {
        }
        
        public GetFileRequestBody(string path) {
            this.path = path;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFileResponse", Namespace="http://cali.eventkalender/", Order=0)]
        public Eventkalender.WS.ConsoleApp.EventkalenderReference.GetFileResponseBody Body;
        
        public GetFileResponse() {
        }
        
        public GetFileResponse(Eventkalender.WS.ConsoleApp.EventkalenderReference.GetFileResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://cali.eventkalender/")]
    public partial class GetFileResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetFileResult;
        
        public GetFileResponseBody() {
        }
        
        public GetFileResponseBody(string GetFileResult) {
            this.GetFileResult = GetFileResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddFile", Namespace="http://cali.eventkalender/", Order=0)]
        public Eventkalender.WS.ConsoleApp.EventkalenderReference.AddFileRequestBody Body;
        
        public AddFileRequest() {
        }
        
        public AddFileRequest(Eventkalender.WS.ConsoleApp.EventkalenderReference.AddFileRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://cali.eventkalender/")]
    public partial class AddFileRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string path;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string content;
        
        public AddFileRequestBody() {
        }
        
        public AddFileRequestBody(string path, string content) {
            this.path = path;
            this.content = content;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddFileResponse", Namespace="http://cali.eventkalender/", Order=0)]
        public Eventkalender.WS.ConsoleApp.EventkalenderReference.AddFileResponseBody Body;
        
        public AddFileResponse() {
        }
        
        public AddFileResponse(Eventkalender.WS.ConsoleApp.EventkalenderReference.AddFileResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AddFileResponseBody {
        
        public AddFileResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetNationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetNation", Namespace="http://cali.eventkalender/", Order=0)]
        public Eventkalender.WS.ConsoleApp.EventkalenderReference.GetNationRequestBody Body;
        
        public GetNationRequest() {
        }
        
        public GetNationRequest(Eventkalender.WS.ConsoleApp.EventkalenderReference.GetNationRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://cali.eventkalender/")]
    public partial class GetNationRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public GetNationRequestBody() {
        }
        
        public GetNationRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetNationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetNationResponse", Namespace="http://cali.eventkalender/", Order=0)]
        public Eventkalender.WS.ConsoleApp.EventkalenderReference.GetNationResponseBody Body;
        
        public GetNationResponse() {
        }
        
        public GetNationResponse(Eventkalender.WS.ConsoleApp.EventkalenderReference.GetNationResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://cali.eventkalender/")]
    public partial class GetNationResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Eventkalender.WS.ConsoleApp.EventkalenderReference.Nation GetNationResult;
        
        public GetNationResponseBody() {
        }
        
        public GetNationResponseBody(Eventkalender.WS.ConsoleApp.EventkalenderReference.Nation GetNationResult) {
            this.GetNationResult = GetNationResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetNationsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetNations", Namespace="http://cali.eventkalender/", Order=0)]
        public Eventkalender.WS.ConsoleApp.EventkalenderReference.GetNationsRequestBody Body;
        
        public GetNationsRequest() {
        }
        
        public GetNationsRequest(Eventkalender.WS.ConsoleApp.EventkalenderReference.GetNationsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetNationsRequestBody {
        
        public GetNationsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetNationsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetNationsResponse", Namespace="http://cali.eventkalender/", Order=0)]
        public Eventkalender.WS.ConsoleApp.EventkalenderReference.GetNationsResponseBody Body;
        
        public GetNationsResponse() {
        }
        
        public GetNationsResponse(Eventkalender.WS.ConsoleApp.EventkalenderReference.GetNationsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://cali.eventkalender/")]
    public partial class GetNationsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Eventkalender.WS.ConsoleApp.EventkalenderReference.Nation[] GetNationsResult;
        
        public GetNationsResponseBody() {
        }
        
        public GetNationsResponseBody(Eventkalender.WS.ConsoleApp.EventkalenderReference.Nation[] GetNationsResult) {
            this.GetNationsResult = GetNationsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddNationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddNation", Namespace="http://cali.eventkalender/", Order=0)]
        public Eventkalender.WS.ConsoleApp.EventkalenderReference.AddNationRequestBody Body;
        
        public AddNationRequest() {
        }
        
        public AddNationRequest(Eventkalender.WS.ConsoleApp.EventkalenderReference.AddNationRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://cali.eventkalender/")]
    public partial class AddNationRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        public AddNationRequestBody() {
        }
        
        public AddNationRequestBody(string name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddNationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddNationResponse", Namespace="http://cali.eventkalender/", Order=0)]
        public Eventkalender.WS.ConsoleApp.EventkalenderReference.AddNationResponseBody Body;
        
        public AddNationResponse() {
        }
        
        public AddNationResponse(Eventkalender.WS.ConsoleApp.EventkalenderReference.AddNationResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AddNationResponseBody {
        
        public AddNationResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddEventRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddEvent", Namespace="http://cali.eventkalender/", Order=0)]
        public Eventkalender.WS.ConsoleApp.EventkalenderReference.AddEventRequestBody Body;
        
        public AddEventRequest() {
        }
        
        public AddEventRequest(Eventkalender.WS.ConsoleApp.EventkalenderReference.AddEventRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://cali.eventkalender/")]
    public partial class AddEventRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string summary;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.DateTime startTime;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.DateTime endTime;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int nationId;
        
        public AddEventRequestBody() {
        }
        
        public AddEventRequestBody(string name, string summary, System.DateTime startTime, System.DateTime endTime, int nationId) {
            this.name = name;
            this.summary = summary;
            this.startTime = startTime;
            this.endTime = endTime;
            this.nationId = nationId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddEventResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddEventResponse", Namespace="http://cali.eventkalender/", Order=0)]
        public Eventkalender.WS.ConsoleApp.EventkalenderReference.AddEventResponseBody Body;
        
        public AddEventResponse() {
        }
        
        public AddEventResponse(Eventkalender.WS.ConsoleApp.EventkalenderReference.AddEventResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AddEventResponseBody {
        
        public AddEventResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEventRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetEvent", Namespace="http://cali.eventkalender/", Order=0)]
        public Eventkalender.WS.ConsoleApp.EventkalenderReference.GetEventRequestBody Body;
        
        public GetEventRequest() {
        }
        
        public GetEventRequest(Eventkalender.WS.ConsoleApp.EventkalenderReference.GetEventRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://cali.eventkalender/")]
    public partial class GetEventRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public GetEventRequestBody() {
        }
        
        public GetEventRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEventResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetEventResponse", Namespace="http://cali.eventkalender/", Order=0)]
        public Eventkalender.WS.ConsoleApp.EventkalenderReference.GetEventResponseBody Body;
        
        public GetEventResponse() {
        }
        
        public GetEventResponse(Eventkalender.WS.ConsoleApp.EventkalenderReference.GetEventResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://cali.eventkalender/")]
    public partial class GetEventResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Eventkalender.WS.ConsoleApp.EventkalenderReference.Event GetEventResult;
        
        public GetEventResponseBody() {
        }
        
        public GetEventResponseBody(Eventkalender.WS.ConsoleApp.EventkalenderReference.Event GetEventResult) {
            this.GetEventResult = GetEventResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEventsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetEvents", Namespace="http://cali.eventkalender/", Order=0)]
        public Eventkalender.WS.ConsoleApp.EventkalenderReference.GetEventsRequestBody Body;
        
        public GetEventsRequest() {
        }
        
        public GetEventsRequest(Eventkalender.WS.ConsoleApp.EventkalenderReference.GetEventsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetEventsRequestBody {
        
        public GetEventsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEventsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetEventsResponse", Namespace="http://cali.eventkalender/", Order=0)]
        public Eventkalender.WS.ConsoleApp.EventkalenderReference.GetEventsResponseBody Body;
        
        public GetEventsResponse() {
        }
        
        public GetEventsResponse(Eventkalender.WS.ConsoleApp.EventkalenderReference.GetEventsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://cali.eventkalender/")]
    public partial class GetEventsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Eventkalender.WS.ConsoleApp.EventkalenderReference.Event[] GetEventsResult;
        
        public GetEventsResponseBody() {
        }
        
        public GetEventsResponseBody(Eventkalender.WS.ConsoleApp.EventkalenderReference.Event[] GetEventsResult) {
            this.GetEventsResult = GetEventsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddPersonRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddPerson", Namespace="http://cali.eventkalender/", Order=0)]
        public Eventkalender.WS.ConsoleApp.EventkalenderReference.AddPersonRequestBody Body;
        
        public AddPersonRequest() {
        }
        
        public AddPersonRequest(Eventkalender.WS.ConsoleApp.EventkalenderReference.AddPersonRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://cali.eventkalender/")]
    public partial class AddPersonRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string firstName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string lastName;
        
        public AddPersonRequestBody() {
        }
        
        public AddPersonRequestBody(string firstName, string lastName) {
            this.firstName = firstName;
            this.lastName = lastName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddPersonResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddPersonResponse", Namespace="http://cali.eventkalender/", Order=0)]
        public Eventkalender.WS.ConsoleApp.EventkalenderReference.AddPersonResponseBody Body;
        
        public AddPersonResponse() {
        }
        
        public AddPersonResponse(Eventkalender.WS.ConsoleApp.EventkalenderReference.AddPersonResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AddPersonResponseBody {
        
        public AddPersonResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPersonRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPerson", Namespace="http://cali.eventkalender/", Order=0)]
        public Eventkalender.WS.ConsoleApp.EventkalenderReference.GetPersonRequestBody Body;
        
        public GetPersonRequest() {
        }
        
        public GetPersonRequest(Eventkalender.WS.ConsoleApp.EventkalenderReference.GetPersonRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://cali.eventkalender/")]
    public partial class GetPersonRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public GetPersonRequestBody() {
        }
        
        public GetPersonRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPersonResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPersonResponse", Namespace="http://cali.eventkalender/", Order=0)]
        public Eventkalender.WS.ConsoleApp.EventkalenderReference.GetPersonResponseBody Body;
        
        public GetPersonResponse() {
        }
        
        public GetPersonResponse(Eventkalender.WS.ConsoleApp.EventkalenderReference.GetPersonResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://cali.eventkalender/")]
    public partial class GetPersonResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Eventkalender.WS.ConsoleApp.EventkalenderReference.Person GetPersonResult;
        
        public GetPersonResponseBody() {
        }
        
        public GetPersonResponseBody(Eventkalender.WS.ConsoleApp.EventkalenderReference.Person GetPersonResult) {
            this.GetPersonResult = GetPersonResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPersonsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPersons", Namespace="http://cali.eventkalender/", Order=0)]
        public Eventkalender.WS.ConsoleApp.EventkalenderReference.GetPersonsRequestBody Body;
        
        public GetPersonsRequest() {
        }
        
        public GetPersonsRequest(Eventkalender.WS.ConsoleApp.EventkalenderReference.GetPersonsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetPersonsRequestBody {
        
        public GetPersonsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPersonsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPersonsResponse", Namespace="http://cali.eventkalender/", Order=0)]
        public Eventkalender.WS.ConsoleApp.EventkalenderReference.GetPersonsResponseBody Body;
        
        public GetPersonsResponse() {
        }
        
        public GetPersonsResponse(Eventkalender.WS.ConsoleApp.EventkalenderReference.GetPersonsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://cali.eventkalender/")]
    public partial class GetPersonsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Eventkalender.WS.ConsoleApp.EventkalenderReference.Person[] GetPersonsResult;
        
        public GetPersonsResponseBody() {
        }
        
        public GetPersonsResponseBody(Eventkalender.WS.ConsoleApp.EventkalenderReference.Person[] GetPersonsResult) {
            this.GetPersonsResult = GetPersonsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface EventkalenderServiceSoapChannel : Eventkalender.WS.ConsoleApp.EventkalenderReference.EventkalenderServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EventkalenderServiceSoapClient : System.ServiceModel.ClientBase<Eventkalender.WS.ConsoleApp.EventkalenderReference.EventkalenderServiceSoap>, Eventkalender.WS.ConsoleApp.EventkalenderReference.EventkalenderServiceSoap {
        
        public EventkalenderServiceSoapClient() {
        }
        
        public EventkalenderServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EventkalenderServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EventkalenderServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EventkalenderServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Eventkalender.WS.ConsoleApp.EventkalenderReference.GetFileResponse Eventkalender.WS.ConsoleApp.EventkalenderReference.EventkalenderServiceSoap.GetFile(Eventkalender.WS.ConsoleApp.EventkalenderReference.GetFileRequest request) {
            return base.Channel.GetFile(request);
        }
        
        public string GetFile(string path) {
            Eventkalender.WS.ConsoleApp.EventkalenderReference.GetFileRequest inValue = new Eventkalender.WS.ConsoleApp.EventkalenderReference.GetFileRequest();
            inValue.Body = new Eventkalender.WS.ConsoleApp.EventkalenderReference.GetFileRequestBody();
            inValue.Body.path = path;
            Eventkalender.WS.ConsoleApp.EventkalenderReference.GetFileResponse retVal = ((Eventkalender.WS.ConsoleApp.EventkalenderReference.EventkalenderServiceSoap)(this)).GetFile(inValue);
            return retVal.Body.GetFileResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Eventkalender.WS.ConsoleApp.EventkalenderReference.GetFileResponse> Eventkalender.WS.ConsoleApp.EventkalenderReference.EventkalenderServiceSoap.GetFileAsync(Eventkalender.WS.ConsoleApp.EventkalenderReference.GetFileRequest request) {
            return base.Channel.GetFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<Eventkalender.WS.ConsoleApp.EventkalenderReference.GetFileResponse> GetFileAsync(string path) {
            Eventkalender.WS.ConsoleApp.EventkalenderReference.GetFileRequest inValue = new Eventkalender.WS.ConsoleApp.EventkalenderReference.GetFileRequest();
            inValue.Body = new Eventkalender.WS.ConsoleApp.EventkalenderReference.GetFileRequestBody();
            inValue.Body.path = path;
            return ((Eventkalender.WS.ConsoleApp.EventkalenderReference.EventkalenderServiceSoap)(this)).GetFileAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Eventkalender.WS.ConsoleApp.EventkalenderReference.AddFileResponse Eventkalender.WS.ConsoleApp.EventkalenderReference.EventkalenderServiceSoap.AddFile(Eventkalender.WS.ConsoleApp.EventkalenderReference.AddFileRequest request) {
            return base.Channel.AddFile(request);
        }
        
        public void AddFile(string path, string content) {
            Eventkalender.WS.ConsoleApp.EventkalenderReference.AddFileRequest inValue = new Eventkalender.WS.ConsoleApp.EventkalenderReference.AddFileRequest();
            inValue.Body = new Eventkalender.WS.ConsoleApp.EventkalenderReference.AddFileRequestBody();
            inValue.Body.path = path;
            inValue.Body.content = content;
            Eventkalender.WS.ConsoleApp.EventkalenderReference.AddFileResponse retVal = ((Eventkalender.WS.ConsoleApp.EventkalenderReference.EventkalenderServiceSoap)(this)).AddFile(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Eventkalender.WS.ConsoleApp.EventkalenderReference.AddFileResponse> Eventkalender.WS.ConsoleApp.EventkalenderReference.EventkalenderServiceSoap.AddFileAsync(Eventkalender.WS.ConsoleApp.EventkalenderReference.AddFileRequest request) {
            return base.Channel.AddFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<Eventkalender.WS.ConsoleApp.EventkalenderReference.AddFileResponse> AddFileAsync(string path, string content) {
            Eventkalender.WS.ConsoleApp.EventkalenderReference.AddFileRequest inValue = new Eventkalender.WS.ConsoleApp.EventkalenderReference.AddFileRequest();
            inValue.Body = new Eventkalender.WS.ConsoleApp.EventkalenderReference.AddFileRequestBody();
            inValue.Body.path = path;
            inValue.Body.content = content;
            return ((Eventkalender.WS.ConsoleApp.EventkalenderReference.EventkalenderServiceSoap)(this)).AddFileAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Eventkalender.WS.ConsoleApp.EventkalenderReference.GetNationResponse Eventkalender.WS.ConsoleApp.EventkalenderReference.EventkalenderServiceSoap.GetNation(Eventkalender.WS.ConsoleApp.EventkalenderReference.GetNationRequest request) {
            return base.Channel.GetNation(request);
        }
        
        public Eventkalender.WS.ConsoleApp.EventkalenderReference.Nation GetNation(int id) {
            Eventkalender.WS.ConsoleApp.EventkalenderReference.GetNationRequest inValue = new Eventkalender.WS.ConsoleApp.EventkalenderReference.GetNationRequest();
            inValue.Body = new Eventkalender.WS.ConsoleApp.EventkalenderReference.GetNationRequestBody();
            inValue.Body.id = id;
            Eventkalender.WS.ConsoleApp.EventkalenderReference.GetNationResponse retVal = ((Eventkalender.WS.ConsoleApp.EventkalenderReference.EventkalenderServiceSoap)(this)).GetNation(inValue);
            return retVal.Body.GetNationResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Eventkalender.WS.ConsoleApp.EventkalenderReference.GetNationResponse> Eventkalender.WS.ConsoleApp.EventkalenderReference.EventkalenderServiceSoap.GetNationAsync(Eventkalender.WS.ConsoleApp.EventkalenderReference.GetNationRequest request) {
            return base.Channel.GetNationAsync(request);
        }
        
        public System.Threading.Tasks.Task<Eventkalender.WS.ConsoleApp.EventkalenderReference.GetNationResponse> GetNationAsync(int id) {
            Eventkalender.WS.ConsoleApp.EventkalenderReference.GetNationRequest inValue = new Eventkalender.WS.ConsoleApp.EventkalenderReference.GetNationRequest();
            inValue.Body = new Eventkalender.WS.ConsoleApp.EventkalenderReference.GetNationRequestBody();
            inValue.Body.id = id;
            return ((Eventkalender.WS.ConsoleApp.EventkalenderReference.EventkalenderServiceSoap)(this)).GetNationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Eventkalender.WS.ConsoleApp.EventkalenderReference.GetNationsResponse Eventkalender.WS.ConsoleApp.EventkalenderReference.EventkalenderServiceSoap.GetNations(Eventkalender.WS.ConsoleApp.EventkalenderReference.GetNationsRequest request) {
            return base.Channel.GetNations(request);
        }
        
        public Eventkalender.WS.ConsoleApp.EventkalenderReference.Nation[] GetNations() {
            Eventkalender.WS.ConsoleApp.EventkalenderReference.GetNationsRequest inValue = new Eventkalender.WS.ConsoleApp.EventkalenderReference.GetNationsRequest();
            inValue.Body = new Eventkalender.WS.ConsoleApp.EventkalenderReference.GetNationsRequestBody();
            Eventkalender.WS.ConsoleApp.EventkalenderReference.GetNationsResponse retVal = ((Eventkalender.WS.ConsoleApp.EventkalenderReference.EventkalenderServiceSoap)(this)).GetNations(inValue);
            return retVal.Body.GetNationsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Eventkalender.WS.ConsoleApp.EventkalenderReference.GetNationsResponse> Eventkalender.WS.ConsoleApp.EventkalenderReference.EventkalenderServiceSoap.GetNationsAsync(Eventkalender.WS.ConsoleApp.EventkalenderReference.GetNationsRequest request) {
            return base.Channel.GetNationsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Eventkalender.WS.ConsoleApp.EventkalenderReference.GetNationsResponse> GetNationsAsync() {
            Eventkalender.WS.ConsoleApp.EventkalenderReference.GetNationsRequest inValue = new Eventkalender.WS.ConsoleApp.EventkalenderReference.GetNationsRequest();
            inValue.Body = new Eventkalender.WS.ConsoleApp.EventkalenderReference.GetNationsRequestBody();
            return ((Eventkalender.WS.ConsoleApp.EventkalenderReference.EventkalenderServiceSoap)(this)).GetNationsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Eventkalender.WS.ConsoleApp.EventkalenderReference.AddNationResponse Eventkalender.WS.ConsoleApp.EventkalenderReference.EventkalenderServiceSoap.AddNation(Eventkalender.WS.ConsoleApp.EventkalenderReference.AddNationRequest request) {
            return base.Channel.AddNation(request);
        }
        
        public void AddNation(string name) {
            Eventkalender.WS.ConsoleApp.EventkalenderReference.AddNationRequest inValue = new Eventkalender.WS.ConsoleApp.EventkalenderReference.AddNationRequest();
            inValue.Body = new Eventkalender.WS.ConsoleApp.EventkalenderReference.AddNationRequestBody();
            inValue.Body.name = name;
            Eventkalender.WS.ConsoleApp.EventkalenderReference.AddNationResponse retVal = ((Eventkalender.WS.ConsoleApp.EventkalenderReference.EventkalenderServiceSoap)(this)).AddNation(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Eventkalender.WS.ConsoleApp.EventkalenderReference.AddNationResponse> Eventkalender.WS.ConsoleApp.EventkalenderReference.EventkalenderServiceSoap.AddNationAsync(Eventkalender.WS.ConsoleApp.EventkalenderReference.AddNationRequest request) {
            return base.Channel.AddNationAsync(request);
        }
        
        public System.Threading.Tasks.Task<Eventkalender.WS.ConsoleApp.EventkalenderReference.AddNationResponse> AddNationAsync(string name) {
            Eventkalender.WS.ConsoleApp.EventkalenderReference.AddNationRequest inValue = new Eventkalender.WS.ConsoleApp.EventkalenderReference.AddNationRequest();
            inValue.Body = new Eventkalender.WS.ConsoleApp.EventkalenderReference.AddNationRequestBody();
            inValue.Body.name = name;
            return ((Eventkalender.WS.ConsoleApp.EventkalenderReference.EventkalenderServiceSoap)(this)).AddNationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Eventkalender.WS.ConsoleApp.EventkalenderReference.AddEventResponse Eventkalender.WS.ConsoleApp.EventkalenderReference.EventkalenderServiceSoap.AddEvent(Eventkalender.WS.ConsoleApp.EventkalenderReference.AddEventRequest request) {
            return base.Channel.AddEvent(request);
        }
        
        public void AddEvent(string name, string summary, System.DateTime startTime, System.DateTime endTime, int nationId) {
            Eventkalender.WS.ConsoleApp.EventkalenderReference.AddEventRequest inValue = new Eventkalender.WS.ConsoleApp.EventkalenderReference.AddEventRequest();
            inValue.Body = new Eventkalender.WS.ConsoleApp.EventkalenderReference.AddEventRequestBody();
            inValue.Body.name = name;
            inValue.Body.summary = summary;
            inValue.Body.startTime = startTime;
            inValue.Body.endTime = endTime;
            inValue.Body.nationId = nationId;
            Eventkalender.WS.ConsoleApp.EventkalenderReference.AddEventResponse retVal = ((Eventkalender.WS.ConsoleApp.EventkalenderReference.EventkalenderServiceSoap)(this)).AddEvent(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Eventkalender.WS.ConsoleApp.EventkalenderReference.AddEventResponse> Eventkalender.WS.ConsoleApp.EventkalenderReference.EventkalenderServiceSoap.AddEventAsync(Eventkalender.WS.ConsoleApp.EventkalenderReference.AddEventRequest request) {
            return base.Channel.AddEventAsync(request);
        }
        
        public System.Threading.Tasks.Task<Eventkalender.WS.ConsoleApp.EventkalenderReference.AddEventResponse> AddEventAsync(string name, string summary, System.DateTime startTime, System.DateTime endTime, int nationId) {
            Eventkalender.WS.ConsoleApp.EventkalenderReference.AddEventRequest inValue = new Eventkalender.WS.ConsoleApp.EventkalenderReference.AddEventRequest();
            inValue.Body = new Eventkalender.WS.ConsoleApp.EventkalenderReference.AddEventRequestBody();
            inValue.Body.name = name;
            inValue.Body.summary = summary;
            inValue.Body.startTime = startTime;
            inValue.Body.endTime = endTime;
            inValue.Body.nationId = nationId;
            return ((Eventkalender.WS.ConsoleApp.EventkalenderReference.EventkalenderServiceSoap)(this)).AddEventAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Eventkalender.WS.ConsoleApp.EventkalenderReference.GetEventResponse Eventkalender.WS.ConsoleApp.EventkalenderReference.EventkalenderServiceSoap.GetEvent(Eventkalender.WS.ConsoleApp.EventkalenderReference.GetEventRequest request) {
            return base.Channel.GetEvent(request);
        }
        
        public Eventkalender.WS.ConsoleApp.EventkalenderReference.Event GetEvent(int id) {
            Eventkalender.WS.ConsoleApp.EventkalenderReference.GetEventRequest inValue = new Eventkalender.WS.ConsoleApp.EventkalenderReference.GetEventRequest();
            inValue.Body = new Eventkalender.WS.ConsoleApp.EventkalenderReference.GetEventRequestBody();
            inValue.Body.id = id;
            Eventkalender.WS.ConsoleApp.EventkalenderReference.GetEventResponse retVal = ((Eventkalender.WS.ConsoleApp.EventkalenderReference.EventkalenderServiceSoap)(this)).GetEvent(inValue);
            return retVal.Body.GetEventResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Eventkalender.WS.ConsoleApp.EventkalenderReference.GetEventResponse> Eventkalender.WS.ConsoleApp.EventkalenderReference.EventkalenderServiceSoap.GetEventAsync(Eventkalender.WS.ConsoleApp.EventkalenderReference.GetEventRequest request) {
            return base.Channel.GetEventAsync(request);
        }
        
        public System.Threading.Tasks.Task<Eventkalender.WS.ConsoleApp.EventkalenderReference.GetEventResponse> GetEventAsync(int id) {
            Eventkalender.WS.ConsoleApp.EventkalenderReference.GetEventRequest inValue = new Eventkalender.WS.ConsoleApp.EventkalenderReference.GetEventRequest();
            inValue.Body = new Eventkalender.WS.ConsoleApp.EventkalenderReference.GetEventRequestBody();
            inValue.Body.id = id;
            return ((Eventkalender.WS.ConsoleApp.EventkalenderReference.EventkalenderServiceSoap)(this)).GetEventAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Eventkalender.WS.ConsoleApp.EventkalenderReference.GetEventsResponse Eventkalender.WS.ConsoleApp.EventkalenderReference.EventkalenderServiceSoap.GetEvents(Eventkalender.WS.ConsoleApp.EventkalenderReference.GetEventsRequest request) {
            return base.Channel.GetEvents(request);
        }
        
        public Eventkalender.WS.ConsoleApp.EventkalenderReference.Event[] GetEvents() {
            Eventkalender.WS.ConsoleApp.EventkalenderReference.GetEventsRequest inValue = new Eventkalender.WS.ConsoleApp.EventkalenderReference.GetEventsRequest();
            inValue.Body = new Eventkalender.WS.ConsoleApp.EventkalenderReference.GetEventsRequestBody();
            Eventkalender.WS.ConsoleApp.EventkalenderReference.GetEventsResponse retVal = ((Eventkalender.WS.ConsoleApp.EventkalenderReference.EventkalenderServiceSoap)(this)).GetEvents(inValue);
            return retVal.Body.GetEventsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Eventkalender.WS.ConsoleApp.EventkalenderReference.GetEventsResponse> Eventkalender.WS.ConsoleApp.EventkalenderReference.EventkalenderServiceSoap.GetEventsAsync(Eventkalender.WS.ConsoleApp.EventkalenderReference.GetEventsRequest request) {
            return base.Channel.GetEventsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Eventkalender.WS.ConsoleApp.EventkalenderReference.GetEventsResponse> GetEventsAsync() {
            Eventkalender.WS.ConsoleApp.EventkalenderReference.GetEventsRequest inValue = new Eventkalender.WS.ConsoleApp.EventkalenderReference.GetEventsRequest();
            inValue.Body = new Eventkalender.WS.ConsoleApp.EventkalenderReference.GetEventsRequestBody();
            return ((Eventkalender.WS.ConsoleApp.EventkalenderReference.EventkalenderServiceSoap)(this)).GetEventsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Eventkalender.WS.ConsoleApp.EventkalenderReference.AddPersonResponse Eventkalender.WS.ConsoleApp.EventkalenderReference.EventkalenderServiceSoap.AddPerson(Eventkalender.WS.ConsoleApp.EventkalenderReference.AddPersonRequest request) {
            return base.Channel.AddPerson(request);
        }
        
        public void AddPerson(string firstName, string lastName) {
            Eventkalender.WS.ConsoleApp.EventkalenderReference.AddPersonRequest inValue = new Eventkalender.WS.ConsoleApp.EventkalenderReference.AddPersonRequest();
            inValue.Body = new Eventkalender.WS.ConsoleApp.EventkalenderReference.AddPersonRequestBody();
            inValue.Body.firstName = firstName;
            inValue.Body.lastName = lastName;
            Eventkalender.WS.ConsoleApp.EventkalenderReference.AddPersonResponse retVal = ((Eventkalender.WS.ConsoleApp.EventkalenderReference.EventkalenderServiceSoap)(this)).AddPerson(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Eventkalender.WS.ConsoleApp.EventkalenderReference.AddPersonResponse> Eventkalender.WS.ConsoleApp.EventkalenderReference.EventkalenderServiceSoap.AddPersonAsync(Eventkalender.WS.ConsoleApp.EventkalenderReference.AddPersonRequest request) {
            return base.Channel.AddPersonAsync(request);
        }
        
        public System.Threading.Tasks.Task<Eventkalender.WS.ConsoleApp.EventkalenderReference.AddPersonResponse> AddPersonAsync(string firstName, string lastName) {
            Eventkalender.WS.ConsoleApp.EventkalenderReference.AddPersonRequest inValue = new Eventkalender.WS.ConsoleApp.EventkalenderReference.AddPersonRequest();
            inValue.Body = new Eventkalender.WS.ConsoleApp.EventkalenderReference.AddPersonRequestBody();
            inValue.Body.firstName = firstName;
            inValue.Body.lastName = lastName;
            return ((Eventkalender.WS.ConsoleApp.EventkalenderReference.EventkalenderServiceSoap)(this)).AddPersonAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Eventkalender.WS.ConsoleApp.EventkalenderReference.GetPersonResponse Eventkalender.WS.ConsoleApp.EventkalenderReference.EventkalenderServiceSoap.GetPerson(Eventkalender.WS.ConsoleApp.EventkalenderReference.GetPersonRequest request) {
            return base.Channel.GetPerson(request);
        }
        
        public Eventkalender.WS.ConsoleApp.EventkalenderReference.Person GetPerson(int id) {
            Eventkalender.WS.ConsoleApp.EventkalenderReference.GetPersonRequest inValue = new Eventkalender.WS.ConsoleApp.EventkalenderReference.GetPersonRequest();
            inValue.Body = new Eventkalender.WS.ConsoleApp.EventkalenderReference.GetPersonRequestBody();
            inValue.Body.id = id;
            Eventkalender.WS.ConsoleApp.EventkalenderReference.GetPersonResponse retVal = ((Eventkalender.WS.ConsoleApp.EventkalenderReference.EventkalenderServiceSoap)(this)).GetPerson(inValue);
            return retVal.Body.GetPersonResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Eventkalender.WS.ConsoleApp.EventkalenderReference.GetPersonResponse> Eventkalender.WS.ConsoleApp.EventkalenderReference.EventkalenderServiceSoap.GetPersonAsync(Eventkalender.WS.ConsoleApp.EventkalenderReference.GetPersonRequest request) {
            return base.Channel.GetPersonAsync(request);
        }
        
        public System.Threading.Tasks.Task<Eventkalender.WS.ConsoleApp.EventkalenderReference.GetPersonResponse> GetPersonAsync(int id) {
            Eventkalender.WS.ConsoleApp.EventkalenderReference.GetPersonRequest inValue = new Eventkalender.WS.ConsoleApp.EventkalenderReference.GetPersonRequest();
            inValue.Body = new Eventkalender.WS.ConsoleApp.EventkalenderReference.GetPersonRequestBody();
            inValue.Body.id = id;
            return ((Eventkalender.WS.ConsoleApp.EventkalenderReference.EventkalenderServiceSoap)(this)).GetPersonAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Eventkalender.WS.ConsoleApp.EventkalenderReference.GetPersonsResponse Eventkalender.WS.ConsoleApp.EventkalenderReference.EventkalenderServiceSoap.GetPersons(Eventkalender.WS.ConsoleApp.EventkalenderReference.GetPersonsRequest request) {
            return base.Channel.GetPersons(request);
        }
        
        public Eventkalender.WS.ConsoleApp.EventkalenderReference.Person[] GetPersons() {
            Eventkalender.WS.ConsoleApp.EventkalenderReference.GetPersonsRequest inValue = new Eventkalender.WS.ConsoleApp.EventkalenderReference.GetPersonsRequest();
            inValue.Body = new Eventkalender.WS.ConsoleApp.EventkalenderReference.GetPersonsRequestBody();
            Eventkalender.WS.ConsoleApp.EventkalenderReference.GetPersonsResponse retVal = ((Eventkalender.WS.ConsoleApp.EventkalenderReference.EventkalenderServiceSoap)(this)).GetPersons(inValue);
            return retVal.Body.GetPersonsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Eventkalender.WS.ConsoleApp.EventkalenderReference.GetPersonsResponse> Eventkalender.WS.ConsoleApp.EventkalenderReference.EventkalenderServiceSoap.GetPersonsAsync(Eventkalender.WS.ConsoleApp.EventkalenderReference.GetPersonsRequest request) {
            return base.Channel.GetPersonsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Eventkalender.WS.ConsoleApp.EventkalenderReference.GetPersonsResponse> GetPersonsAsync() {
            Eventkalender.WS.ConsoleApp.EventkalenderReference.GetPersonsRequest inValue = new Eventkalender.WS.ConsoleApp.EventkalenderReference.GetPersonsRequest();
            inValue.Body = new Eventkalender.WS.ConsoleApp.EventkalenderReference.GetPersonsRequestBody();
            return ((Eventkalender.WS.ConsoleApp.EventkalenderReference.EventkalenderServiceSoap)(this)).GetPersonsAsync(inValue);
        }
    }
}
